config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root'static_pages#index'
  resources :static_pages
  resources :settings
  resources:users
  resources :comments 
  resources :cards 

  get '/forgot', to:'users#forgot'
  post '/sendpass', to:'users#sendpass'



  get '/signup', to:'users#new'
  post'/signup',to:'users#create'
  get    '/login',   to: 'sessions#new'   
  post   '/login',   to: 'sessions#create'   
  delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
        <p> s3660068</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%=link_to"NEWS+", root_path, id:"logo"%>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                 <li style="float: left"><%=link_to logged_in? ? "Wellcome #{current_user.name} !" : "" , '#' %></li>
                 <li><%=link_to"|", '#' %></li>
                <li id="hover"><%=link_to"Home",    root_path %></li>


                <li class="dropdown"> 
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        New <b class="caret"></b>
                        </a> 
                        <ul class="dropdown-menu">
                           <% @forum_new.each do |fn| %>

                            <li><%= link_to "#{fn.name}", '' %></li>
                            <%end%>
                        </ul>
                    </li>


                <% if logged_in? %>
                    <li class="dropdown"> 
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                        </a> 
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "settings", '/settings' %></li>
                            <li class = "divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: :delete %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%=render'layouts/shim'%>
  </head>
  <body>
    <%= render'layouts/header'%>
    <div class= "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>